services:
  server:
    build: .
    container_name: node-server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis-db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo_data: